import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/analysis_result.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateAndPrintReport(AnalysisResult result) async {
    final pdf = pw.Document();

    final date = DateFormat('MMMM dd, yyyy - hh:mm a').format(DateTime.now());

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Dental Analysis Report',
                        style: pw.TextStyle(
                          fontSize: 24,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue800,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text('Generated by AI Dentist Assistant',
                          style: const pw.TextStyle(
                              fontSize: 14, color: PdfColors.grey700)),
                    ],
                  ),
                  pw.Container(
                    width: 50,
                    height: 50,
                    decoration: const pw.BoxDecoration(
                      color: PdfColors.blue50,
                      shape: pw.BoxShape.circle,
                    ),
                    child: pw.Center(
                      child: pw.Text('AI',
                          style: pw.TextStyle(
                              fontSize: 24,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.blue800)),
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(color: PdfColors.blue200),
              pw.SizedBox(height: 20),
              
              // Patient Info / Date
              pw.Text('Date: $date', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
              pw.SizedBox(height: 20),

              // Summary Section
              pw.Container(
                padding: const pw.EdgeInsets.all(16),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                  border: pw.Border.all(color: PdfColors.blue200),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Analysis Summary', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                    pw.SizedBox(height: 12),
                    _buildReportRow('Alignment:', result.alignmentTip),
                    _buildReportRow('Symmetry:', result.symmetryTip),
                    _buildReportRow('Gum Health:', result.gumHealth),
                    _buildReportRow('Cavity Detection:', result.cavityStatus),
                    _buildReportRow('Staining:', result.stainingStatus),
                    _buildReportRow('Gum Visibility:', result.gumVisibility),
                  ],
                ),
              ),
              
              pw.SizedBox(height: 24),
              pw.Text('AI-Generated Explanation', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
              pw.SizedBox(height: 12),
              pw.Text('Based on the uploaded dental scan, the AI has detected specific oral health indicators. '
                  'The analysis highlights key areas such as alignment, gum health, and potential cavity signs. '
                  'Please review the detailed metrics above and consult your dental provider for a comprehensive clinical diagnosis.',
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey800)),
              
              pw.SizedBox(height: 24),
              pw.Text('Recommendations', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
              pw.SizedBox(height: 12),
              pw.Text(result.report['recommendations'] ?? 'Consult a professional dentist for personalized advice.', style: const pw.TextStyle(fontSize: 12)),
              
              pw.Spacer(),
              pw.Divider(color: PdfColors.grey300),
              pw.SizedBox(height: 8),
              pw.Center(
                child: pw.Text('Disclaimer: This is an AI-generated provisional report and does not replace professional medical diagnosis.',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Dental_Analysis_Report.pdf',
    );
  }

  static pw.Widget _buildReportRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12, color: PdfColors.grey800)),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 12, color: PdfColors.black)),
          ),
        ],
      ),
    );
  }
}
